/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AiDraftBuilderRouteImport } from './routes/ai-draft-builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IncidentsCreateRouteImport } from './routes/incidents.create'
import { Route as IncidentsIdRouteImport } from './routes/incidents.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDraftBuilderRoute = AiDraftBuilderRouteImport.update({
  id: '/ai-draft-builder',
  path: '/ai-draft-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsCreateRoute = IncidentsCreateRouteImport.update({
  id: '/incidents/create',
  path: '/incidents/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIdRoute = IncidentsIdRouteImport.update({
  id: '/incidents/$id',
  path: '/incidents/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-draft-builder': typeof AiDraftBuilderRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/login': typeof LoginRoute
  '/incidents/$id': typeof IncidentsIdRoute
  '/incidents/create': typeof IncidentsCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-draft-builder': typeof AiDraftBuilderRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/login': typeof LoginRoute
  '/incidents/$id': typeof IncidentsIdRoute
  '/incidents/create': typeof IncidentsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-draft-builder': typeof AiDraftBuilderRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/login': typeof LoginRoute
  '/incidents/$id': typeof IncidentsIdRoute
  '/incidents/create': typeof IncidentsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-draft-builder'
    | '/dashboard'
    | '/departments'
    | '/login'
    | '/incidents/$id'
    | '/incidents/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-draft-builder'
    | '/dashboard'
    | '/departments'
    | '/login'
    | '/incidents/$id'
    | '/incidents/create'
  id:
    | '__root__'
    | '/'
    | '/ai-draft-builder'
    | '/dashboard'
    | '/departments'
    | '/login'
    | '/incidents/$id'
    | '/incidents/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiDraftBuilderRoute: typeof AiDraftBuilderRoute
  DashboardRoute: typeof DashboardRoute
  DepartmentsRoute: typeof DepartmentsRoute
  LoginRoute: typeof LoginRoute
  IncidentsIdRoute: typeof IncidentsIdRoute
  IncidentsCreateRoute: typeof IncidentsCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-draft-builder': {
      id: '/ai-draft-builder'
      path: '/ai-draft-builder'
      fullPath: '/ai-draft-builder'
      preLoaderRoute: typeof AiDraftBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/create': {
      id: '/incidents/create'
      path: '/incidents/create'
      fullPath: '/incidents/create'
      preLoaderRoute: typeof IncidentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/$id': {
      id: '/incidents/$id'
      path: '/incidents/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof IncidentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiDraftBuilderRoute: AiDraftBuilderRoute,
  DashboardRoute: DashboardRoute,
  DepartmentsRoute: DepartmentsRoute,
  LoginRoute: LoginRoute,
  IncidentsIdRoute: IncidentsIdRoute,
  IncidentsCreateRoute: IncidentsCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
